[package]
name = "cert-service-practice"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
axum = "0.8.9"
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
chrono = { version = "0.4.44", features = ["serde"] }
dotenvy = "0.15.7"
rcgen = "0.14.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "uuid", "chrono", "macros"] }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
tower-http = { version = "0.6.10", features = ["trace", "request-id"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
uuid = { version = "1.23.1", features = ["serde", "v7"] }
x509-parser = "0.18.1"

[dev-dependencies]
reqwest = { version = "0.13.3", features = ["json"] }
