apiVersion: v1
kind: Secret
metadata:
  name: cert-service-secret
  namespace: cert-service
type: Opaque
data:
  # base64 encoded values
  # echo -n "your-value" | base64
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEBkYjo1NDMyL2NlcnRfc2VydmljZQ==
  TLS_CERT_PATH: Y2VydHMvY2VydC5wZW0=
  TLS_KEY_PATH: Y2VydHMva2V5LnBlbQ==